### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by energizer91** [strumwolf/delete-deployment-environment#10]
When I am trying to clean deployments and environments, looks like deployments are deleted successfully, but when action is trying to delete environment, it gets `Resource not accessible by integration`. Probably it's because the project is using SSO and lacks some right, but looks like token has all necessary roles.

**Comment by V3lop5** [comment]
Running into the same issue. 

Did you find a solution @energizer91?

**Comment by strumwolf** [comment]
The token provided by GitHub during the action does not have enough permissions to delete the environment. It has permissions to delete the deployments.

You will need to provide a token that has broader permissions.

**Comment by energizer91** [comment]
yes, I understand that, but what means "broader"? It's said that we need repo permissions, which github token has. But what else then?

**Comment by strumwolf** [comment]
It's not obvious to me from the documentation or when creating a key which permissions under the repo scope are required. I can do some testing to narrow it down.

**Comment by energizer91** [comment]
I was having a conversation with support and they said you need to have `admin write:org` right to delete environments

**Comment by strumwolf** [comment]
Nice. When I get around to testing I'll be sure to try with and without that permission. It would have been nice if they included that in the documentation other than repo level scope.

**Comment by V3lop5** [comment]
Thanks alot for your research!

Currently I'm using your action with [`continue-on-error: true`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error). 

The environment under [Environments](https://github.com/fhac-ewi/grid-optimizer/deployments) is deleted by this action. So its not visible for public any more. 
It's only visible under [Environments Tab in Settings](https://github.com/fhac-ewi/grid-optimizer/settings/environments). (I might delete them from time to time by hand.)

For me that works and I don't have to provide a token with special permissions. 

Maybe you can think of adding an option like "skip deleting from settings page" so this action is easy to use without special token needed.

**Comment by energizer91** [comment]
Actually I also using `continue-on-error`, however if you ask your environments with REST API you'll see that these empty environments still exist. So it could be possible to write a custom cron script to clean them

**Comment by strumwolf** [comment]
If you add `onlyRemoveDeployments: true` it will remove the the environment under the `Environments` section but won't try to remove the environment tab that show in `Settings`. This should not require specially permissions.

**Comment by V3lop5** [comment]
You are absolutly right. I simply can't read. 
I added some lines in your README. Maybe it helps people like me and prevents issues like this one.

Thanks for this nice action and helping me/us out!

**Comment by strumwolf** [comment]
👍  Thanks for the PR!

**Comment by HuyAms** [comment]
I got the same issue. Could you tell me which exact permission I need?
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by grantnorwood** [comment]
Some additional step-by-step instructions would definitely help!  I gave my standard `$GITHUB_TOKEN` full permissions, but it still fails when attempting to delete an environment:

```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

```
Error: Resource not accessible by integration
```

I tried created a GitHub app and generating a new client secret, which I added to my repository's Actions secrets:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/707463/208310150-7adfaa70-9f45-47c7-9a2a-a038418ef470.png">

And I passed that secret to the `token` input as shown below:

```yml
- name: 🧼 Clean up GitHub environment after closing PR
  uses: strumwolf/delete-deployment-environment@v2.2.3
  if: |
    (github.event.action == 'unlabeled' && github.event.label.name == 'staging')
    || (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'staging'))

  with:
    # The provided token needs permission for admin write:org
    token: ${{ secrets.GH_APP_TOKEN }}
    environment: remixaustin-com-pr-${{ github.event.number }}
    ref: ${{ github.ref_name }}
```

... but that gives me a `Bad Credential` error when deleting the environment in my workflow.  I suspect this is because I haven't traded my secret for a JWT?

I'd love some help understanding how to give your awesome action the correct permissions!
