### ISSUE TITLE
Need Help Dynamically Getting Environment Name

### ISSUE THREAD

**Issue by bruschke** [strumwolf/delete-deployment-environment#18]
I appreciate this action.  In our organization I just discovered that we have been creating environments automatically with each PR but we have not been deleting them when the PR is closed and the branch is deleted.  I was hoping to use this action to start to clean up after ourselves.  Our environments are all named the same [app-name]-staging-pr[github pull request number].  I'm new to github actions, do you have any ideas on how I could dynamically get the pull request number for the branch that is being deleted?

**Comment by IronSean** [comment]
The way we do it is to have a github action that triggers on pr closes (either merge or close will trigger) and then clean up. Since it's triggered by a PR action, it'll be in the context of a PR and have the PR number so you just have to format it the same.

```yaml
on:
  pull_request:
    branches: [main]
    types: [closed, converted_to_draft]
    
# delete deployment slot 'APP_NAME-staging-pr${{ github.event.number }}'
```
