### ISSUE TITLE
Specify only deployments for a given ref

### ISSUE THREAD

**Issue by syntaqx** [strumwolf/delete-deployment-environment#20]
It would be awesome to have an input that optionally allowed only specifying the deployments `ref` so it's not simply for all deployments  of a given environment:

```sh
gh api \
  -H "Accept: application/vnd.github.v3+json" \
  /repos/OWNER/REPO/deployments?ref=my-branch
```

Allowing me to:

```yaml
- uses: strumwolf/delete-deployment-environment@v2
   with:
      token: ${{ secrets.GITHUB_TOKEN }}
      environment: staging
      ref: my-branch
      onlyRemoveDeployments: true
```

Which would only delete deployments to `staging` for a `my-branch` (which often correlates to a deployment to an environment for a given branch)

**Comment by strumwolf** [comment]
Thanks for the suggestion @syntaqx . Feel free to create a PR. Otherwise I will look into making the suggested option when I have time.

**Comment by iohcidnal** [comment]
Hi @strumwolf. I've submitted a PR for this issue. Please let me know if you need anything from me. Thanks so much!

**Comment by jlian** [comment]
I'm getting this error when trying to use it 

```
Warning: Unexpected input(s) 'ref', valid inputs are ['token', 'environment', 'onlyRemoveDeployments', 'onlyDeactivateDeployments']
```

![image](https://user-images.githubusercontent.com/2320572/188264237-46ab0fe5-e5dd-49b1-b44b-bc1b1960d619.png)

My workflow 

```yaml
  deactivate:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preview
          ref: ${{ github.head_ref }}
          onlyDeactivateDeployments: true
```

I think `action.yml` needs to be updated?
