### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by jasonkuhrt** [strumwolf/delete-deployment-environment#30]
Getting this error, not sure what's up? How do I fix this?

<img width="505" alt="CleanShot 2022-09-17 at 22 33 57@2x" src="https://user-images.githubusercontent.com/284476/190883113-af40bbf4-0017-4e55-abe2-b415d3ef7894.png">

**Comment by strumwolf** [comment]
Did you pass in a value for `ref` in the action?

**Comment by jasonkuhrt** [comment]
No, my code looks like:

```yaml
  teardown-github-environment:
    needs: detect-affected-apps
    if: needs.detect-affected-apps.outputs.is-none == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{fromJson(needs.detect-affected-apps.outputs.apps)}}
    steps:
      - uses: actions/checkout@v3
      - name: Teardown GitHub Environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{secrets.GH_TOKEN_ENHANCED}}
          environment: ${{matrix.name}}:preview-${{github.event.number}}
```
