### ISSUE TITLE
Resource not accessible by integration despite correct JWT

### ISSUE THREAD

**Issue by p0fi** [strumwolf/delete-deployment-environment#38]
First off: **I am aware of #10** 

I have the exact same problem but it somehow does not get solved by using the JWT of a GitHub App with sufficient permissions.

Workflow file:

```yaml
- name: 🎟 Get GitHub App token
  uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
  id: get-token
  with:
    app-id: ${{ secrets.GH_APP_ID }}
    private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

- name: Print Token
  run: echo ${{ steps.get-token.outputs.token }} | sed 's/./& /g'

- uses: strumwolf/delete-deployment-environment@v2
  with:
    token: ${{ steps.get-token.outputs.token }}
    environment: pr-${{ github.event.pull_request.number }}
```

Output:
```
Run strumwolf/delete-deployment-environment@v2
 with:
    token: ***
    environment: pr-9
Found 4 deployments
deactivating all 4 deployments in environment pr-9
deleting all 4 deployments in environment pr-9
Error: Error deleting environment
Error: Resource not accessible by integration
```

As you can see I print the token for debug purposes in one step. If I now take this token and use it with the GitHub REST API deleting the environment works perfectly.

Curl command:
```bash
curl \
  -X DELETE \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ghs_************************************"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/<org>/<repo>/environments/pr-9
```

Why can't the action delete the environment when the REST API can with the exact same token? 😢

**Comment by p0fi** [comment]
#### Update
I implemented the action myself using the `github-script` action from [here](https://github.com/actions/github-script) and everything works fine with the token also given to the action. I don't really know why. Here is my script code

```yaml
- name: 🧼 Clean up Environment
  uses: actions/github-script@v6
  with:
    github-token: ${{ steps.get-token.outputs.token }}
    script: |
      // Get all deployments
      const deployments = await github.rest.repos.listDeployments({
        owner: context.repo.owner,
        repo: context.repo.repo,
      });
      const deployment_ids = deployments.data.map(a => a.id);
      for (const deploymentId of deployment_ids){
        // Deactivate deployment
        await github.rest.repos.createDeploymentStatus({
          owner: context.repo.owner,
          repo: context.repo.repo,
          deployment_id: deploymentId,
          state: 'inactive',
        });
        // Delete deployment
        await github.rest.repos.deleteDeployment({
          owner: context.repo.owner,
          repo: context.repo.repo,
          deployment_id: deploymentId,
        });
      }
      // Delete environment 🚀
      const res = await github.rest.repos.deleteAnEnvironment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        environment_name: 'pr-${{ github.event.pull_request.number }}',
      })
```

While im having a working solution now Im still wondering why this action here does not do the job 🤔
