### ISSUE TITLE
Error: Error deleting environment

### ISSUE THREAD

**Issue by davidfilat** [strumwolf/delete-deployment-environment#39]
I'm trying to run the action to delete an existing environment. The action does work in deleting the deployment, however it does not delete the environment. Did I miss anything?

Here is the action configuration:
```yaml
    delete:
        name: Delete deploy environment
        runs-on: ubuntu-latest
        needs: destroy
        steps:
            - name: 🎟 Get GitHub App token
              uses: navikt/github-app-token-generator@v1
              id: get-token
              with:
                  app-id: ${{ secrets.GITHUP_APP_ID }}
                  private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

            - name: Delete environment
              uses: strumwolf/delete-deployment-environment@v2
              with:
                  token: ${{ steps.get-token.outputs.token }}
                  environment: ${{ github.head_ref }}
```

<img width="1812" alt="CleanShot 2023-03-23 at 11 24 22@2x" src="https://user-images.githubusercontent.com/1475163/227159281-9e7ea82b-3fed-4a52-ba53-6101e220dfe6.png">
